### ISSUE TITLE
Disable Notification Centre Alerts Config

### ISSUE THREAD

**Issue by solicomo** [deanishe/alfred-pwgen#3]
Thanks for this awesome workflow. 

But the alerts show in the NC every time I gen a new password are really annoying.

Is there any config to disable them?

**Comment by deanishe** [comment]
There isn't currently an option to disable them, no, but you can delete the 3 Post Notification actions in the workflow.

I'll add the option in the next version.

**Comment by deanishe** [comment]
Added in v2.0
