### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ChainsawBaby** [deanishe/alfred-pwgen#8]
Python is using 100% of CPU usage and doesn't stop after a while
```
cwd
/Users/MartinBratteng/Google Drive/dot_files/Alfred.alfredpreferences/workflows/user.workflow.805B770E-C1E8-40BD-8238-4A600B431C77
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
txt
/System/Library/Frameworks/Python.framework/Versions/2.7/Python
txt
/usr/lib/dyld
txt
/private/var/db/dyld/dyld_shared_cache_x86_64h
0
/dev/null
1
/dev/null
2
/dev/null
3
/Users/MartinBratteng/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-pwgen/net.deanishe.alfred-pwgen.log
4
/Users/MartinBratteng/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Data/net.deanishe.alfred-pwgen/net.deanishe.alfred-pwgen.log
```

I'm running MacOS 10.12.4, Alfred 3.3.1 and pwgen 2.0

**Comment by deanishe** [comment]
This issue [has already been fixed](https://github.com/deanishe/alfred-pwgen/releases).

Please ensure you're using the latest version before posting a bug report.

(Probably best to download the update by hand: the bug also affects the update mechanism.)

**Comment by deanishe** [comment]
Oh, you might want to run [this workflow](https://github.com/deanishe/alfred-fixum/).

It should fix any other workflows you have that are affected by the bug (it's in a common workflow library) until their developers push official updates.
