### ISSUE TITLE
generated password doesn't show up in clipboard history

### ISSUE THREAD

**Issue by peterkraume** [deanishe/alfred-pwgen#9]
I've just installed pwgen 2.1.1 and now the generated passwords don't show up in my clipboard history as it used to be in previous versions. Bug or feature?
Alfred version  is 3.5.1.

**Comment by deanishe** [comment]
Feature.

Passwords are now marked as "concealed" by default, so (compliant) clipboard managers don't record them.

Use `⌥↩` to copy a password "publicly".

**Comment by peterkraume** [comment]
Good to know. Thx for the fast answer!
